name: Docker Image CI

on:
  workflow_dispatch:


permissions:
  contents: write
  pull-requests: write

env:
  PROJECT_ID: affable-bivouac-474215-h5
  REGION: us-central1
  REPOSITORY: my-repo
  IMAGE_NAME: my-app
  INSTANCE_NAME: instance-20251031-232551
  ZONE: us-central1-a
  ARTIFACTREGISTRY: us-central1-docker.pkg.dev


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet
      - name: Build and push image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
