name: Docker Image CI

on:
  workflow_dispatch:


permissions:
  contents: write
  pull-requests: write

env:
  PROJECT_ID: affable-bivouac-474215-h5
  REGION: us-central1
  REPOSITORY: my-repo
  IMAGE_NAME: my-app
  INSTANCE_NAME: instance-20251031-232551
  ZONE: us-central1-A
  ARTIFACTREGISTRY: us-central1-docker.pkg.dev
  CLUSTER_NAME: autopilot-cluster-1


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Cloud SDK & kubectl
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ env.PROJECT_ID }}
          # install kubectl
          install_components: kubectl

      
      - name: get gke cred
        run: gcloud container clusters get-credentials autopilot-cluster-1 --zone us-east1 --project affable-bivouac-474215-h5

        
      #- name: Configure Docker for Google Artifact Registry
      #  run: gcloud auth configure-docker  ${{ env.REGION }}-docker.pkg.dev
      #- name: Build and push image
      #  run: |
       #   docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/my-repo/my-app:latest .
        #  docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/my-repo/my-app:latest
          
       

      # Deploy the Docker image to the GKE cluster
      - name: 'Deploy to GKE'
        run: |-
          kubectl set image deployment/deployment-1 cont_iris-2=my-app:latest --record
          
          kubectl rollout status deployment/deployment-1
          kubectl get services -o wide

