name: Docker Image CI

on:
  workflow_dispatch:


permissions:
  contents: write
  pull-requests: write

env:
  PROJECT_ID: affable-bivouac-474215-h5
  REGION: us-central1
  REPOSITORY: my-repo
  IMAGE_NAME: my-app
  INSTANCE_NAME: instance-20251031-232551
  ZONE: us-central1-a
  ARTIFACTREGISTRY: us-central1-docker.pkg.dev


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: PROJECT_ID
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push image
        run: |
          docker build -t REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE_NAME:latest .
          docker push REGION-docker.pkg.dev/PROJECT_ID/REPO_NAME/IMAGE_NAME:latest
